// Birthplaces for the time correction: longitude (for local mean time) and the IANA time zone (for the clock
// history, summer time included). Korean names first, then English, then extra search words.
// [id, 이름, English, 나라/지역, longitude, time zone, aliases]
type Row = [string, string, string, string, number, string, string?];

const KR = "Asia/Seoul";
const ROWS: Row[] = [
  // 대한민국
  ["seoul", "서울", "Seoul", "대한민국", 126.98, KR],
  ["incheon", "인천", "Incheon", "대한민국", 126.7, KR],
  ["suwon", "수원", "Suwon", "경기", 127.03, KR, "경기도"],
  ["seongnam", "성남", "Seongnam", "경기", 127.13, KR, "분당"],
  ["goyang", "고양", "Goyang", "경기", 126.83, KR, "일산"],
  ["yongin", "용인", "Yongin", "경기", 127.18, KR],
  ["bucheon", "부천", "Bucheon", "경기", 126.78, KR],
  ["ansan", "안산", "Ansan", "경기", 126.83, KR],
  ["anyang", "안양", "Anyang", "경기", 126.95, KR],
  ["uijeongbu", "의정부", "Uijeongbu", "경기", 127.04, KR],
  ["pyeongtaek", "평택", "Pyeongtaek", "경기", 127.11, KR],
  ["paju", "파주", "Paju", "경기", 126.78, KR],
  ["gimpo", "김포", "Gimpo", "경기", 126.72, KR],
  ["hwaseong", "화성", "Hwaseong", "경기", 126.83, KR, "동탄"],
  ["chuncheon", "춘천", "Chuncheon", "강원", 127.73, KR, "강원도"],
  ["wonju", "원주", "Wonju", "강원", 127.95, KR],
  ["gangneung", "강릉", "Gangneung", "강원", 128.9, KR],
  ["sokcho", "속초", "Sokcho", "강원", 128.59, KR],
  ["cheongju", "청주", "Cheongju", "충북", 127.49, KR, "충청북도"],
  ["chungju", "충주", "Chungju", "충북", 127.93, KR],
  ["daejeon", "대전", "Daejeon", "대한민국", 127.38, KR],
  ["sejong", "세종", "Sejong", "대한민국", 127.29, KR],
  ["cheonan", "천안", "Cheonan", "충남", 127.15, KR, "충청남도"],
  ["asan", "아산", "Asan", "충남", 127.0, KR],
  ["gongju", "공주", "Gongju", "충남", 127.12, KR],
  ["jeonju", "전주", "Jeonju", "전북", 127.15, KR, "전라북도"],
  ["gunsan", "군산", "Gunsan", "전북", 126.74, KR],
  ["iksan", "익산", "Iksan", "전북", 126.96, KR],
  ["gwangju", "광주", "Gwangju", "대한민국", 126.85, KR, "광주광역시"],
  ["mokpo", "목포", "Mokpo", "전남", 126.39, KR, "전라남도"],
  ["yeosu", "여수", "Yeosu", "전남", 127.66, KR],
  ["suncheon", "순천", "Suncheon", "전남", 127.49, KR],
  ["daegu", "대구", "Daegu", "대한민국", 128.6, KR],
  ["pohang", "포항", "Pohang", "경북", 129.36, KR, "경상북도"],
  ["gyeongju", "경주", "Gyeongju", "경북", 129.22, KR],
  ["gumi", "구미", "Gumi", "경북", 128.34, KR],
  ["andong", "안동", "Andong", "경북", 128.73, KR],
  ["busan", "부산", "Busan", "대한민국", 129.08, KR, "pusan"],
  ["ulsan", "울산", "Ulsan", "대한민국", 129.31, KR],
  ["changwon", "창원", "Changwon", "경남", 128.68, KR, "마산 진해 경상남도"],
  ["jinju", "진주", "Jinju", "경남", 128.11, KR],
  ["gimhae", "김해", "Gimhae", "경남", 128.89, KR],
  ["tongyeong", "통영", "Tongyeong", "경남", 128.43, KR],
  ["geoje", "거제", "Geoje", "경남", 128.62, KR],
  ["jeju", "제주", "Jeju", "제주", 126.53, KR, "제주도"],
  ["seogwipo", "서귀포", "Seogwipo", "제주", 126.56, KR],
  ["pyongyang", "평양", "Pyongyang", "북한", 125.75, "Asia/Pyongyang"],
  ["kaesong", "개성", "Kaesong", "북한", 126.55, "Asia/Pyongyang"],
  ["hamhung", "함흥", "Hamhung", "북한", 127.54, "Asia/Pyongyang"],
  ["sinuiju", "신의주", "Sinuiju", "북한", 124.4, "Asia/Pyongyang"],
  // 일본·중국·대만·몽골·러시아 극동
  ["tokyo", "도쿄", "Tokyo", "일본", 139.69, "Asia/Tokyo", "동경"],
  ["osaka", "오사카", "Osaka", "일본", 135.5, "Asia/Tokyo"],
  ["nagoya", "나고야", "Nagoya", "일본", 136.91, "Asia/Tokyo"],
  ["fukuoka", "후쿠오카", "Fukuoka", "일본", 130.4, "Asia/Tokyo"],
  ["sapporo", "삿포로", "Sapporo", "일본", 141.35, "Asia/Tokyo"],
  ["kyoto", "교토", "Kyoto", "일본", 135.77, "Asia/Tokyo"],
  ["beijing", "베이징", "Beijing", "중국", 116.4, "Asia/Shanghai", "북경"],
  ["shanghai", "상하이", "Shanghai", "중국", 121.47, "Asia/Shanghai", "상해"],
  ["tianjin", "톈진", "Tianjin", "중국", 117.2, "Asia/Shanghai", "천진"],
  ["qingdao", "칭다오", "Qingdao", "중국", 120.38, "Asia/Shanghai", "청도"],
  ["dalian", "다롄", "Dalian", "중국", 121.61, "Asia/Shanghai", "대련"],
  ["shenyang", "선양", "Shenyang", "중국", 123.43, "Asia/Shanghai", "심양"],
  ["harbin", "하얼빈", "Harbin", "중국", 126.63, "Asia/Shanghai"],
  ["yanji", "옌지", "Yanji", "중국", 129.51, "Asia/Shanghai", "연길 연변"],
  ["guangzhou", "광저우", "Guangzhou", "중국", 113.26, "Asia/Shanghai", "광주 중국"],
  ["shenzhen", "선전", "Shenzhen", "중국", 114.06, "Asia/Shanghai", "심천"],
  ["chengdu", "청두", "Chengdu", "중국", 104.07, "Asia/Shanghai", "성도"],
  ["wuhan", "우한", "Wuhan", "중국", 114.31, "Asia/Shanghai"],
  ["xian", "시안", "Xi'an", "중국", 108.94, "Asia/Shanghai", "서안"],
  ["chongqing", "충칭", "Chongqing", "중국", 106.55, "Asia/Shanghai", "중경"],
  ["hongkong", "홍콩", "Hong Kong", "중국", 114.17, "Asia/Hong_Kong"],
  ["macau", "마카오", "Macau", "중국", 113.54, "Asia/Macau"],
  ["taipei", "타이베이", "Taipei", "대만", 121.56, "Asia/Taipei", "대북"],
  ["kaohsiung", "가오슝", "Kaohsiung", "대만", 120.3, "Asia/Taipei"],
  ["ulaanbaatar", "울란바토르", "Ulaanbaatar", "몽골", 106.92, "Asia/Ulaanbaatar"],
  ["vladivostok", "블라디보스토크", "Vladivostok", "러시아", 131.89, "Asia/Vladivostok"],
  // 동남아·남아시아·중앙아시아·중동
  ["bangkok", "방콕", "Bangkok", "태국", 100.5, "Asia/Bangkok"],
  ["hanoi", "하노이", "Hanoi", "베트남", 105.85, "Asia/Ho_Chi_Minh"],
  ["hochiminh", "호찌민", "Ho Chi Minh City", "베트남", 106.63, "Asia/Ho_Chi_Minh", "호치민 사이공"],
  ["danang", "다낭", "Da Nang", "베트남", 108.22, "Asia/Ho_Chi_Minh"],
  ["manila", "마닐라", "Manila", "필리핀", 120.98, "Asia/Manila"],
  ["cebu", "세부", "Cebu", "필리핀", 123.89, "Asia/Manila"],
  ["singapore", "싱가포르", "Singapore", "싱가포르", 103.82, "Asia/Singapore", "싱가폴"],
  ["kualalumpur", "쿠알라룸푸르", "Kuala Lumpur", "말레이시아", 101.69, "Asia/Kuala_Lumpur"],
  ["jakarta", "자카르타", "Jakarta", "인도네시아", 106.85, "Asia/Jakarta"],
  ["bali", "발리", "Bali (Denpasar)", "인도네시아", 115.22, "Asia/Makassar", "덴파사르"],
  ["phnompenh", "프놈펜", "Phnom Penh", "캄보디아", 104.92, "Asia/Phnom_Penh"],
  ["yangon", "양곤", "Yangon", "미얀마", 96.2, "Asia/Yangon"],
  ["vientiane", "비엔티안", "Vientiane", "라오스", 102.63, "Asia/Vientiane"],
  ["newdelhi", "뉴델리", "New Delhi", "인도", 77.21, "Asia/Kolkata", "델리"],
  ["mumbai", "뭄바이", "Mumbai", "인도", 72.88, "Asia/Kolkata"],
  ["bangalore", "벵갈루루", "Bengaluru", "인도", 77.59, "Asia/Kolkata", "방갈로르"],
  ["kathmandu", "카트만두", "Kathmandu", "네팔", 85.32, "Asia/Kathmandu"],
  ["dhaka", "다카", "Dhaka", "방글라데시", 90.41, "Asia/Dhaka"],
  ["karachi", "카라치", "Karachi", "파키스탄", 67.01, "Asia/Karachi"],
  ["tashkent", "타슈켄트", "Tashkent", "우즈베키스탄", 69.24, "Asia/Tashkent"],
  ["almaty", "알마티", "Almaty", "카자흐스탄", 76.89, "Asia/Almaty"],
  ["dubai", "두바이", "Dubai", "아랍에미리트", 55.27, "Asia/Dubai"],
  ["riyadh", "리야드", "Riyadh", "사우디아라비아", 46.72, "Asia/Riyadh"],
  ["doha", "도하", "Doha", "카타르", 51.53, "Asia/Qatar"],
  ["tehran", "테헤란", "Tehran", "이란", 51.39, "Asia/Tehran"],
  ["istanbul", "이스탄불", "Istanbul", "튀르키예", 28.98, "Europe/Istanbul", "터키"],
  ["telaviv", "텔아비브", "Tel Aviv", "이스라엘", 34.78, "Asia/Jerusalem", "예루살렘"],
  ["cairo", "카이로", "Cairo", "이집트", 31.24, "Africa/Cairo"],
  ["johannesburg", "요하네스버그", "Johannesburg", "남아프리카공화국", 28.05, "Africa/Johannesburg"],
  ["nairobi", "나이로비", "Nairobi", "케냐", 36.82, "Africa/Nairobi"],
  ["lagos", "라고스", "Lagos", "나이지리아", 3.38, "Africa/Lagos"],
  // 오세아니아
  ["sydney", "시드니", "Sydney", "호주", 151.21, "Australia/Sydney"],
  ["melbourne", "멜버른", "Melbourne", "호주", 144.96, "Australia/Melbourne", "멜번"],
  ["brisbane", "브리즈번", "Brisbane", "호주", 153.03, "Australia/Brisbane"],
  ["perth", "퍼스", "Perth", "호주", 115.86, "Australia/Perth"],
  ["adelaide", "애들레이드", "Adelaide", "호주", 138.6, "Australia/Adelaide"],
  ["auckland", "오클랜드", "Auckland", "뉴질랜드", 174.76, "Pacific/Auckland"],
  ["christchurch", "크라이스트처치", "Christchurch", "뉴질랜드", 172.64, "Pacific/Auckland"],
  ["guam", "괌", "Guam", "미국", 144.75, "Pacific/Guam"],
  ["honolulu", "호놀룰루", "Honolulu", "미국 하와이", -157.86, "Pacific/Honolulu", "하와이"],
  // 북미
  ["newyork", "뉴욕", "New York", "미국", -74.01, "America/New_York"],
  ["newjersey", "뉴저지", "New Jersey (Newark)", "미국", -74.17, "America/New_York", "뉴어크"],
  ["boston", "보스턴", "Boston", "미국", -71.06, "America/New_York"],
  ["philadelphia", "필라델피아", "Philadelphia", "미국", -75.17, "America/New_York"],
  ["washington", "워싱턴 D.C.", "Washington, D.C.", "미국", -77.04, "America/New_York"],
  ["atlanta", "애틀랜타", "Atlanta", "미국", -84.39, "America/New_York"],
  ["miami", "마이애미", "Miami", "미국", -80.19, "America/New_York"],
  ["chicago", "시카고", "Chicago", "미국", -87.63, "America/Chicago"],
  ["dallas", "댈러스", "Dallas", "미국", -96.8, "America/Chicago", "달라스"],
  ["houston", "휴스턴", "Houston", "미국", -95.37, "America/Chicago"],
  ["denver", "덴버", "Denver", "미국", -104.99, "America/Denver"],
  ["phoenix", "피닉스", "Phoenix", "미국", -112.07, "America/Phoenix"],
  ["lasvegas", "라스베이거스", "Las Vegas", "미국", -115.14, "America/Los_Angeles", "라스베가스"],
  ["losangeles", "로스앤젤레스", "Los Angeles", "미국", -118.24, "America/Los_Angeles", "LA 엘에이"],
  ["sandiego", "샌디에이고", "San Diego", "미국", -117.16, "America/Los_Angeles"],
  ["sanfrancisco", "샌프란시스코", "San Francisco", "미국", -122.42, "America/Los_Angeles"],
  ["sanjose", "새너제이", "San Jose", "미국", -121.89, "America/Los_Angeles", "산호세"],
  ["seattle", "시애틀", "Seattle", "미국", -122.33, "America/Los_Angeles"],
  ["portland", "포틀랜드", "Portland", "미국", -122.68, "America/Los_Angeles"],
  ["anchorage", "앵커리지", "Anchorage", "미국 알래스카", -149.9, "America/Anchorage", "알래스카"],
  ["toronto", "토론토", "Toronto", "캐나다", -79.38, "America/Toronto"],
  ["montreal", "몬트리올", "Montreal", "캐나다", -73.57, "America/Toronto"],
  ["vancouver", "밴쿠버", "Vancouver", "캐나다", -123.12, "America/Vancouver"],
  ["calgary", "캘거리", "Calgary", "캐나다", -114.07, "America/Edmonton"],
  ["mexicocity", "멕시코시티", "Mexico City", "멕시코", -99.13, "America/Mexico_City"],
  // 남미
  ["saopaulo", "상파울루", "São Paulo", "브라질", -46.63, "America/Sao_Paulo", "상파울로"],
  ["riodejaneiro", "리우데자네이루", "Rio de Janeiro", "브라질", -43.17, "America/Sao_Paulo"],
  ["buenosaires", "부에노스아이레스", "Buenos Aires", "아르헨티나", -58.38, "America/Argentina/Buenos_Aires"],
  ["santiago", "산티아고", "Santiago", "칠레", -70.67, "America/Santiago"],
  ["lima", "리마", "Lima", "페루", -77.04, "America/Lima"],
  ["bogota", "보고타", "Bogotá", "콜롬비아", -74.07, "America/Bogota"],
  ["asuncion", "아순시온", "Asunción", "파라과이", -57.58, "America/Asuncion"],
  // 유럽
  ["london", "런던", "London", "영국", -0.13, "Europe/London"],
  ["manchester", "맨체스터", "Manchester", "영국", -2.24, "Europe/London"],
  ["dublin", "더블린", "Dublin", "아일랜드", -6.26, "Europe/Dublin"],
  ["paris", "파리", "Paris", "프랑스", 2.35, "Europe/Paris"],
  ["lyon", "리옹", "Lyon", "프랑스", 4.84, "Europe/Paris"],
  ["berlin", "베를린", "Berlin", "독일", 13.4, "Europe/Berlin"],
  ["frankfurt", "프랑크푸르트", "Frankfurt", "독일", 8.68, "Europe/Berlin"],
  ["munich", "뮌헨", "Munich", "독일", 11.58, "Europe/Berlin"],
  ["hamburg", "함부르크", "Hamburg", "독일", 9.99, "Europe/Berlin"],
  ["madrid", "마드리드", "Madrid", "스페인", -3.7, "Europe/Madrid"],
  ["barcelona", "바르셀로나", "Barcelona", "스페인", 2.17, "Europe/Madrid"],
  ["lisbon", "리스본", "Lisbon", "포르투갈", -9.14, "Europe/Lisbon"],
  ["rome", "로마", "Rome", "이탈리아", 12.5, "Europe/Rome"],
  ["milan", "밀라노", "Milan", "이탈리아", 9.19, "Europe/Rome"],
  ["amsterdam", "암스테르담", "Amsterdam", "네덜란드", 4.9, "Europe/Amsterdam"],
  ["brussels", "브뤼셀", "Brussels", "벨기에", 4.35, "Europe/Brussels"],
  ["zurich", "취리히", "Zurich", "스위스", 8.54, "Europe/Zurich"],
  ["geneva", "제네바", "Geneva", "스위스", 6.14, "Europe/Zurich"],
  ["vienna", "빈", "Vienna", "오스트리아", 16.37, "Europe/Vienna", "비엔나"],
  ["prague", "프라하", "Prague", "체코", 14.42, "Europe/Prague"],
  ["warsaw", "바르샤바", "Warsaw", "폴란드", 21.01, "Europe/Warsaw"],
  ["budapest", "부다페스트", "Budapest", "헝가리", 19.04, "Europe/Budapest"],
  ["athens", "아테네", "Athens", "그리스", 23.73, "Europe/Athens"],
  ["stockholm", "스톡홀름", "Stockholm", "스웨덴", 18.07, "Europe/Stockholm"],
  ["oslo", "오슬로", "Oslo", "노르웨이", 10.75, "Europe/Oslo"],
  ["copenhagen", "코펜하겐", "Copenhagen", "덴마크", 12.57, "Europe/Copenhagen"],
  ["helsinki", "헬싱키", "Helsinki", "핀란드", 24.94, "Europe/Helsinki"],
  ["kyiv", "키이우", "Kyiv", "우크라이나", 30.52, "Europe/Kiev", "키예프"],
  ["moscow", "모스크바", "Moscow", "러시아", 37.62, "Europe/Moscow"],
  ["saintpetersburg", "상트페테르부르크", "Saint Petersburg", "러시아", 30.32, "Europe/Moscow"],
];

export type City = { id: string; name: string; en: string; region: string; lon: number; tz: string; search: string };

export const CITIES: City[] = ROWS.map(([id, name, en, region, lon, tz, aliases = ""]) => ({
  id,
  name,
  en,
  region,
  lon,
  tz,
  search: `${name} ${en} ${region} ${aliases} ${id}`.toLowerCase().replace(/\s+/g, " "),
}));

export const cityById = (id: string) => CITIES.find((c) => c.id === id) ?? CITIES[0];

// An exact name or alias ("LA", "북경") comes first, then names that start with the query, then any match.
export function searchCities(query: string, limit = 8): City[] {
  const q = query.trim().toLowerCase().replace(/\s+/g, " ");
  if (!q) return [];
  const exact = CITIES.filter((c) => c.search.split(" ").includes(q));
  const starts = CITIES.filter((c) => !exact.includes(c) && (c.name.startsWith(q) || c.en.toLowerCase().startsWith(q)));
  const rest = CITIES.filter((c) => !exact.includes(c) && !starts.includes(c) && c.search.includes(q));
  return [...exact, ...starts, ...rest].slice(0, limit);
}
